FROM nginx:latest
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "vim"]
RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
RUN mkdir -p /app/report/jobid
COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80